//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WinkelServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WinkelServiceReference.IGebruikerService")]
    public interface IGebruikerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGebruikerService/Registreer", ReplyAction="http://tempuri.org/IGebruikerService/RegistreerResponse")]
        string Registreer(string gebruikersnaam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGebruikerService/Registreer", ReplyAction="http://tempuri.org/IGebruikerService/RegistreerResponse")]
        System.Threading.Tasks.Task<string> RegistreerAsync(string gebruikersnaam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGebruikerService/Login", ReplyAction="http://tempuri.org/IGebruikerService/LoginResponse")]
        int Login(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGebruikerService/Login", ReplyAction="http://tempuri.org/IGebruikerService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGebruikerServiceChannel : Client.WinkelServiceReference.IGebruikerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GebruikerServiceClient : System.ServiceModel.ClientBase<Client.WinkelServiceReference.IGebruikerService>, Client.WinkelServiceReference.IGebruikerService {
        
        public GebruikerServiceClient() {
        }
        
        public GebruikerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GebruikerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GebruikerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GebruikerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Registreer(string gebruikersnaam) {
            return base.Channel.Registreer(gebruikersnaam);
        }
        
        public System.Threading.Tasks.Task<string> RegistreerAsync(string gebruikersnaam) {
            return base.Channel.RegistreerAsync(gebruikersnaam);
        }
        
        public int Login(int x, int y) {
            return base.Channel.Login(x, y);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(int x, int y) {
            return base.Channel.LoginAsync(x, y);
        }
    }
}
